### ISSUE TITLE
Unsupported Kubernetes Version Error

### ISSUE THREAD

**Issue by Fadi-Almachraki** [datarevenue-berlin/OpenMLOps#108]
Hello, and thank you for this great resource. I'm running into an error while going through the architecture set-up tutorial for AWS. I'm able to successfully run everything including "terraform plan -var-file=my_vars.tfvars". I get the following error when I run "terraform apply -var-file=my_vars.tfvars". Let me know if there's any other helpful information I could provide: 

![image](https://user-images.githubusercontent.com/11321384/150267278-a64153e9-8eeb-4363-8842-94cce5ddb15f.png)

**Comment by bernardolk** [comment]
Hello, in your my_vars file, are you using `kubernetes_version = "1.17"` ? I think AWS deprecated that version for new EKS clusters. See this link https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
Apparently you will have to set it with one version from the least, being the oldest one 1.18.16. Can you try that and see if it works? I can then update the default in the project's my_vars file / documentation.

**Comment by Fadi-Almachraki** [comment]
Thanks for getting back to me and pardon the potentially dumb question. But where should I be trying to change the version? I don't have a kubernetes_version variable in the my_vars file (which is inside the OpenMLOps-AWS repo). Please let me know if you think i'm missing anything.

**Comment by bernardolk** [comment]
You can add a line there for the "kubernetes_version" variable in the file anyway :)
e.g. `kubernetes_version = 1.18.16`

**Comment by Fadi-Almachraki** [comment]
Thank you that worked. But I actually had to do kubernetes_version = 1.18. Otherwise I was getting an error related to not being able to read the version as a number. I'm now dealing with a different error I'll post a new issue about.
