### ISSUE TITLE
error creating EKS Cluster (eks-mlops): InvalidParameterException: unsupported Kubernetes version

### ISSUE THREAD

**Issue by oristides** [datarevenue-berlin/OpenMLOps#109]
I followed steps and I got this error when I do:

terraform apply -var-file=my_vars.tfvars

Error: error creating EKS Cluster (eks-mlops): InvalidParameterException: unsupported Kubernetes version

I dont know what is the problem here and how to debug

**Comment by bernardolk** [comment]
Please check https://github.com/datarevenue-berlin/OpenMLOps/issues/108

**Comment by bernardolk** [comment]
closing duplicate, lets move discussion there
