### ISSUE TITLE
OpenMLOps has no license

### ISSUE THREAD

**Issue by KellyJDavis** [datarevenue-berlin/OpenMLOps#58]
OpenMLOps has no license, according to GitHub[[1](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license)]:

> ...without a license, the default copyright laws apply, meaning that you (Data Revenue) retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

So no one external to Data Revenue can use this repo.

**Comment by pedrocwb** [comment]
Thanks for spotting this @KellyJDavis. We will add the license.

**Comment by pipatth** [comment]
MIT license added
