### ISSUE TITLE
Error creating S3 bucket: BucketAlreadyOwnedByYou

### ISSUE THREAD

**Issue by NhatAnh** [datarevenue-berlin/OpenMLOps#70]
When I try to follow the instruction at https://github.com/datarevenue-berlin/OpenMLOps/blob/master/tutorials/set-up-open-source-production-mlops-architecture-aws.md

I got to the step running: terraform apply -var-file=my_vars.tfvars

But I got: Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
│ 
│   with aws_s3_bucket.mlflow_artifact_root,
│   on main.tf line 11, in resource "aws_s3_bucket" "mlflow_artifact_root":
│   11: resource "aws_s3_bucket" "mlflow_artifact_root"

If I delete the S3 bucket and rerun the command, I got: Error loading state: S3 bucket does not exist.

So maybe it was using that bucket, but then later try to create the bucket again?

**Comment by NhatAnh** [comment]
Thanks, I change backend to "local" in main.tf and that error is gone.
But I got "Error creating VPC: UnauthorizedOperation". I'm pretty sure I have admin permission to create VPC. How can I debug this? Thank you.

**Comment by NhatAnh** [comment]
Hi, I got to the end of the tutorial. But the link https://mlops.pixtavietnam.com/ return 404. While the link https://jupyter.mlops.pixtavietnam.com/ return 401. How do I get the auth link https://mlops.pixtavietnam.com/auth/profile/registration to work? Thanks

**Comment by bernardolk** [comment]
So, your "homepage" won't work unless you have routing rules set for it that lead to a service returning a webpage.
Now, the 401 you are getting in the second URL is normal, since you are not logged in yet.
The third I think is wrong, try `https://mlops.pixtavietnam.com/profile/auth/registration`. If it doesn't work, then you will need to get a log from your oathkeeper pod, to see if the request is hitting

**Comment by NhatAnh** [comment]
When I run: kubectl get pods -n ory
NAME                              READY   STATUS    RESTARTS   AGE
ory-kratos-5f777789c7-5g6r5       0/1     Running   14         66m
ory-kratos-courier-0              1/1     Running   15         66m
ory-kratos-ui-65679f6764-xhwmk    1/1     Running   0          61m
ory-oathkeeper-6bf994cf97-qtk8j   1/1     Running   0          68m
postgres-postgresql-0             1/1     Running   0          67m

But when I try to get log: kubectl -n ory logs -p ory-oathkeeper-6bf994cf97-qtk8j
Error from server (BadRequest): previous terminated container "ory-oathkeeper" in pod "ory-oathkeeper-6bf994cf97-qtk8j" not found

**Comment by NhatAnh** [comment]
Thank you. It seems to work now. For prefect and mlflow subdomain, I don't seem to have to login (after register account at https://mlops.pixtavietnam.com/profile/auth/registration). But for https://jupyter.mlops.pixtavietnam.com/ it shows a login page, but I can't use the login I just created from https://mlops.pixtavietnam.com/profile/auth/registration. It also doesn't have any signup page.

So how do I login to jupyter subdomain?

**Comment by NhatAnh** [comment]
Thanks, it seems to work now. But when I try to start jupyter server, I got timeout error:
```
2021-08-31T06:19:35Z [Normal] pod didn't trigger scale-up (it wouldn't fit if a new node is added):
2021-08-31T06:24:01Z [Warning] 0/3 nodes are available: 1 Insufficient memory, 2 Too many pods.
Spawn failed: pod/jupyter-test did not start in 300 seconds!
```

**Comment by NhatAnh** [comment]
Thank you, I got it almost 100% working. But I got `prefect.exceptions.ClientError: Your Prefect Server instance has no tenants. Create a tenant with `prefect server create-tenant` for pod prefect-server-agent. I think in my previous run, this pod ran fine. How do I fix this one?

**Comment by bernardolk** [comment]
Hmm, checkout this issue, there is some relevant info at the very bottom of the discussion:
https://github.com/datarevenue-berlin/OpenMLOps/issues/67

I hope it helps, but if it doesn't, please tell us :)

**Comment by NhatAnh** [comment]
It seems to have fixed itself overnight :)
Thank you a lot for your help!

**Comment by bernardolk** [comment]
I would say the safest is to destroy, but you can try scaling everything to 0 and then monitor your costs in AWS console to see if they are going up. Would be nice to know if that's an option but I believe they will still charge you :x

**Comment by NhatAnh** [comment]
Hi,
I try to deploy again today. But I got this error:
```
Error: Provider produced inconsistent final plan
When expanding the plan for module.mlops-architecture.module.ambassador[0].helm_release.ambassador[0] to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/helm" produced an invalid new value for .version: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by NhatAnh** [comment]
Hi,
When I tried to run terraform apply again, ory kratos and prefect seems to have problems:
```
ory           ory-kratos-745dbfc959-g2fkv                          0/1     Running            0          22m
ory           ory-kratos-courier-0                                 1/1     Running            1          22m
ory           ory-kratos-ui-d4cb9797-88hsr                         1/1     Running            0          17m
ory           ory-oathkeeper-6d8d9956f4-wznwt                      1/1     Running            0          24m
ory           postgres-postgresql-0                                1/1     Running            0          24m
prefect       prefect-server-agent-7c66444c89-b4wzg                0/1     CrashLoopBackOff   8          24m
prefect       prefect-server-apollo-78d8f89c57-7w7dg               1/1     Running            0          24m
prefect       prefect-server-create-tenant-job-n44n2               0/1     CrashLoopBackOff   9          24m
```

When I `kubectl -n prefect logs prefect-server-create-tenant-job-n44n2`
I got `requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f64fb80b690>: Failed to establish a new connection: [Errno 111] Connection refused'))`

When I run `kubectl -n prefect logs prefect-server-agent-7c66444c89-b4wzg`
```
Your Prefect Server instance has no tenants. Create a tenant with `prefect server create-tenant`
```

When I run `kubectl -n ory describe pod ory-kratos-745dbfc959-g2fkv`
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  18m                   default-scheduler  Successfully assigned ory/ory-kratos-745dbfc959-g2fkv to ip-10-0-3-253.ap-northeast-1.compute.internal
  Normal   Pulling    18m                   kubelet            Pulling image "oryd/kratos:v0.6.3-alpha.1"
  Normal   Pulled     18m                   kubelet            Successfully pulled image "oryd/kratos:v0.6.3-alpha.1" in 5.070344108s
  Normal   Created    18m                   kubelet            Created container kratos
  Normal   Started    18m                   kubelet            Started container kratos
  Warning  Unhealthy  3m25s (x86 over 17m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503
```
