### ISSUE TITLE
How to configure running this framework on local Kubernetes cluster?

### ISSUE THREAD

**Issue by fadishaar84** [datarevenue-berlin/OpenMLOps#75]
Thanks for sharing your OpenMLOps framework. I hope to find some guidance to configure this framework to make it work on our local Kubernetes cluster. What modifications need to be done for each component?

**Comment by bernardolk** [comment]
Hey, @fadishaar84 we are planning on releasing soon our repo for deploying OpenMLOps on minikube, so you can spin up the cluster locally. To answer your question, no modifications are needed inside the OML repo, the only extra step is to run terraform commands through the minikube repo instead through the AWS repo.
We are currently updating / testing that repo, but I will make sure to keep you posted once it's done.

**Comment by bernardolk** [comment]
https://github.com/datarevenue-berlin/OpenMLOps/issues/76 will track this issue

**Comment by pipatth** [comment]
@fadishaar84 We added a tutorial on how to deploy on Minikube. See https://github.com/datarevenue-berlin/OpenMLOps/blob/master/tutorials/set-up-minikube-cluster.md

**Comment by fadishaar84** [comment]
@pipatth Thanks, I will give it a try.
