### ISSUE TITLE
A few questions after following the setup guide

### ISSUE THREAD

**Issue by off99555** [datarevenue-berlin/OpenMLOps#85]
I was following this guide: https://github.com/datarevenue-berlin/OpenMLOps/blob/master/tutorials/set-up-open-source-production-mlops-architecture-aws.md#configuring-the-my_varstfvars-file and have a few questions.

1. Do I need to set `additional_aws_users` field in `my_vars.tfvars` to an empty list if I just have only one user (me)?
![image](https://user-images.githubusercontent.com/15215732/135201042-68538d24-7ab6-40d2-8494-478c19ea9864.png)

2. If I am the only user, do I need to fill in `oauth2_providers`? Or do I just need to make it an empty list? If I need to create a new OAuth application, what should I fill in the `Authorization callback URL` text box? 
![image](https://user-images.githubusercontent.com/15215732/135200544-a0bf8ee7-2abb-4bef-93d9-8df5ee556c69.png)
3. If I set both 2 attributes above to be empty lists and run `terraform init`, it asks me to enter an S3 bucket name. What should I fill in this? If it's related to the `bucket_name` field in the `my_vars.tfvars` file, I've already set it.
![image](https://user-images.githubusercontent.com/15215732/135200893-1437dc08-24df-4dd0-8c96-390aa9957132.png)

**Comment by bernardolk** [comment]
Hi there,

1. No, its not required, it defaults to an empty list.
2. I believe it should also work without this being set, but could you try 
`https://{your_host}/.ory/kratos/public/self-service/methods/oidc/callback/github` ?
3. Actually, this would be the bucket that Terraform stores its state, which is different than the bucket you specify in my_vars.tfvars. You can configure your Terraform backend to local if you don't wish to use S3 for that.
